# Images and labels directory should be relative to train.py
TRAIN_DIR_IMAGES: 'data/splitted_data_combination/train'
TRAIN_DIR_LABELS: 'data/splitted_data_combination/train'
VALID_DIR_IMAGES: 'data/splitted_data_combination/test'
VALID_DIR_LABELS: 'data/splitted_data_combination/test'

# Class names.
CLASSES: [
    '__background__',
    'text_overlap',
    'component_occlusion',
    'missing_image',
    'null_text',
    'element_overflow'
]

# Number of classes (object classes + 1 for background class in Faster RCNN).
NC: 6

# Whether to save the predictions of the validation set while training.
SAVE_VALID_PREDICTION_IMAGES: True
